environment:
    matrix:
        # Windows
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          QTDIR: C:\Qt\5.11\msvc2017_64
          OS: windows
        # Linux
        - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
          OS: linux
          
services:
    - Docker

install:
    # Windows
    - cmd: set PATH=%QTDIR%\bin;C:\Qt\Tools\QtCreator\bin;%PATH%
    - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
    # Linux
    - sh: sudo service docker start
    
build_script:
    # Windows
    - cmd: qmake Gen7TimeFinder.pro
    - cmd: jom -j %NUMBER_OF_PROCESSORS%
    # Linux
    - sh: docker run -w="/app" -v "$(pwd)":/app rabits/qt:5.12-desktop sudo /opt/Qt/5.12.0/gcc_64/bin/qmake
    - sh: docker run -w="/app" -v "$(pwd)":/app rabits/qt:5.12-desktop sudo make -j 4

after_build:
    # Windows
    - cmd: md Gen7TimeFinder-windows
    - cmd: move release\Gen7TimeFinder.exe Gen7TimeFinder-windows\Gen7TimeFinder.exe 
    - cmd: windeployqt --release --no-translations --no-angle --no-plugins --no-opengl-sw Gen7TimeFinder-windows\Gen7TimeFinder.exe
    - cmd: del Gen7TimeFinder-windows\vcredist*.exe
    - cmd: del Gen7TimeFinder-windows\vc_redist*.exe
    - cmd: xcopy /I %QTDIR%\plugins\platforms\qwindows.dll Gen7TimeFinder-windows\platforms\
    - cmd: xcopy /I %QTDIR%\plugins\styles\qwindowsvistastyle.dll Gen7TimeFinder-windows\styles\
    - cmd: 7z a Gen7TimeFinder-windows.zip Gen7TimeFinder-windows\
    # Linux
    - sh: zip -r Gen7TimeFinder-linux.zip Gen7TimeFinder
    
artifacts:
    - path: Gen7TimeFinder-%OS%.zip

deploy:
    provider: GitHub
    auth_token:
        secure: KPKgc2JaeXV8NBnz+72ILmsh7hKA3v7fWYG4D7X4Oxn7zplWJwP/eeWoObEg9YDH
    artifact: Gen7TimeFinder-%OS%.zip
    on:
        APPVEYOR_REPO_TAG: true
